## BASE URL
#
@baseUrl = http://localhost:9090

#
@currentDir = /Users/hidenari-yuda/documents/prac-golang/umerun-resume/server

## Firebase ID Token
#
@firebaseIdToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjUyZmEwZjE2NmJmZjZiODU5N2FjMGFlMDRlNTllZmYxOTk1N2MyYmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVjaHViLXNlYXJjaC10bXAiLCJhdWQiOiJyZWNodWItc2VhcmNoLXRtcCIsImF1dGhfdGltZSI6MTY2MjIxMTQzNSwidXNlcl9pZCI6IjI0NjZiY2NiLTk3NzgtNDcyOC1hZWM2LWMxZWQxMjZkOGE0MyIsInN1YiI6IjI0NjZiY2NiLTk3NzgtNDcyOC1hZWM2LWMxZWQxMjZkOGE0MyIsImlhdCI6MTY2MjIxMTQzNSwiZXhwIjoxNjYyMjE1MDM1LCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.TYBxaeCdMEUXsHbah0zf8jkB6dcCfielHoWjwij4K8Ar5LYkAGsCWDo4A0m-ByE57_uxuc5Q4GjV_p5Sb_Us6n5odj4O6w8RTFLxowjzMcUN3Mhu0wbSBdmSs9hIClldbFLoHm00xgKjbgoAfEZiYWTS5zvHp79ccg_Fd6fmN8PgX0ybB38uEqyzJPkPYVbYhDQfV2SQa0FF_IatNEAzaWV6BJgsP76MJgbSrUA-h__oA-EpGV8Yug14Dquq0sJOpMFewnt-3t-15j2tJPR3KXgGKx6_3i8v-Rj0CG_8IkBEDIkOy-JBhn-8H2FJUWhfWg0soTeT578T1fDRNaCjwg"
## JWT TOKEN from our server.
#
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjUyZmEwZjE2NmJmZjZiODU5N2FjMGFlMDRlNTllZmYxOTk1N2MyYmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVjaHViLXNlYXJjaC10bXAiLCJhdWQiOiJyZWNodWItc2VhcmNoLXRtcCIsImF1dGhfdGltZSI6MTY2MjIxMTQzNSwidXNlcl9pZCI6IjI0NjZiY2NiLTk3NzgtNDcyOC1hZWM2LWMxZWQxMjZkOGE0MyIsInN1YiI6IjI0NjZiY2NiLTk3NzgtNDcyOC1hZWM2LWMxZWQxMjZkOGE0MyIsImlhdCI6MTY2MjIxMTQzNSwiZXhwIjoxNjYyMjE1MDM1LCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.TYBxaeCdMEUXsHbah0zf8jkB6dcCfielHoWjwij4K8Ar5LYkAGsCWDo4A0m-ByE57_uxuc5Q4GjV_p5Sb_Us6n5odj4O6w8RTFLxowjzMcUN3Mhu0wbSBdmSs9hIClldbFLoHm00xgKjbgoAfEZiYWTS5zvHp79ccg_Fd6fmN8PgX0ybB38uEqyzJPkPYVbYhDQfV2SQa0FF_IatNEAzaWV6BJgsP76MJgbSrUA-h__oA-EpGV8Yug14Dquq0sJOpMFewnt-3t-15j2tJPR3KXgGKx6_3i8v-Rj0CG_8IkBEDIkOy-JBhn-8H2FJUWhfWg0soTeT578T1fDRNaCjwg


### signup
#
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "email": "test2@test2222.com",
    "password": "test2222"  
}

### signIn
#
PUT {{baseUrl}}/api/signin HTTP/1.1
Content-Type: application/json

 {
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImY4MDljZmYxMTZlNWJhNzQwNzQ1YmZlZGE1OGUxNmU4MmYzZmQ4MDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdW1lcnVuLXJlc3VtZSIsImF1ZCI6InVtZXJ1bi1yZXN1bWUiLCJhdXRoX3RpbWUiOjE2NjkyMDA2NjQsInVzZXJfaWQiOiI2Rkd2UHJYYzJSUU1Ta3E5bHZDQzFSWXpmaVYyIiwic3ViIjoiNkZHdlByWGMyUlFNU2txOWx2Q0MxUll6ZmlWMiIsImlhdCI6MTY2OTIwNzM1MiwiZXhwIjoxNjY5MjEwOTUyLCJlbWFpbCI6InRlc3RAdGVzdDExMTEuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdDExMTEuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.gEBDcowvLEPPAgvpqh8ysEBQdQ4b_sdSG8JMIMrlAIz6mJqdgJ28MRzo7DFjauHrlMOverS9rkAsz_uUWJ7VPWZq3BOc7U7Dv160eIpyLGd1HSckalINrPys5BRIYyl77BwwQxCqyWMvsdCR2GUiSwoePTHu3LDOSW6tMkuu5T6NZrq5rNBUaOch2EyS-K-RmwULZSnfOlPhocDVE-RxzWiACFY6rHQEN1GwPXOqp6zNhaJhHlmmJX-3llLYJf1Nvn1Es6ElT--_Tp0HP-Tc19Tc3r_fAqRmQetjbWSyDNJhhCiS5c0DufsBPFR3CcJWAqJCvdL_Hz-pB6SGfVgM0Q"
 }

### getProfile
#
GET {{baseUrl}}/api/user/token HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImY4MDljZmYxMTZlNWJhNzQwNzQ1YmZlZGE1OGUxNmU4MmYzZmQ4MDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdW1lcnVuLXJlc3VtZSIsImF1ZCI6InVtZXJ1bi1yZXN1bWUiLCJhdXRoX3RpbWUiOjE2NjkyMDA2NjQsInVzZXJfaWQiOiI2Rkd2UHJYYzJSUU1Ta3E5bHZDQzFSWXpmaVYyIiwic3ViIjoiNkZHdlByWGMyUlFNU2txOWx2Q0MxUll6ZmlWMiIsImlhdCI6MTY2OTIwNzM1MiwiZXhwIjoxNjY5MjEwOTUyLCJlbWFpbCI6InRlc3RAdGVzdDExMTEuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdDExMTEuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.gEBDcowvLEPPAgvpqh8ysEBQdQ4b_sdSG8JMIMrlAIz6mJqdgJ28MRzo7DFjauHrlMOverS9rkAsz_uUWJ7VPWZq3BOc7U7Dv160eIpyLGd1HSckalINrPys5BRIYyl77BwwQxCqyWMvsdCR2GUiSwoePTHu3LDOSW6tMkuu5T6NZrq5rNBUaOch2EyS-K-RmwULZSnfOlPhocDVE-RxzWiACFY6rHQEN1GwPXOqp6zNhaJhHlmmJX-3llLYJf1Nvn1Es6ElT--_Tp0HP-Tc19Tc3r_fAqRmQetjbWSyDNJhhCiS5c0DufsBPFR3CcJWAqJCvdL_Hz-pB6SGfVgM0Q"
}

### 履歴書からテキスト
POST {{baseUrl}}/api/detect/resume/job_seeker HTTP/1.1
