// Specify the version of the protocol

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: competitor.proto

// Specify package name to avoid name collision

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Competitor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MediaId       int64  `protobuf:"varint,3,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Competitor    string `protobuf:"bytes,4,opt,name=competitor,proto3" json:"competitor,omitempty"`
	Bolume        int64  `protobuf:"varint,5,opt,name=bolume,proto3" json:"bolume,omitempty"`
	Rank          int64  `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	SeoDifficulty int64  `protobuf:"varint,7,opt,name=seo_difficulty,json=seoDifficulty,proto3" json:"seo_difficulty,omitempty"`
	Url           string `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool   `protobuf:"varint,11,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
}

func (x *Competitor) Reset() {
	*x = Competitor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Competitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Competitor) ProtoMessage() {}

func (x *Competitor) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Competitor.ProtoReflect.Descriptor instead.
func (*Competitor) Descriptor() ([]byte, []int) {
	return file_competitor_proto_rawDescGZIP(), []int{0}
}

func (x *Competitor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Competitor) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Competitor) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *Competitor) GetCompetitor() string {
	if x != nil {
		return x.Competitor
	}
	return ""
}

func (x *Competitor) GetBolume() int64 {
	if x != nil {
		return x.Bolume
	}
	return 0
}

func (x *Competitor) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Competitor) GetSeoDifficulty() int64 {
	if x != nil {
		return x.SeoDifficulty
	}
	return 0
}

func (x *Competitor) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Competitor) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Competitor) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Competitor) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type CompetitorList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompetitorList []*Competitor `protobuf:"bytes,1,rep,name=competitor_list,json=competitorList,proto3" json:"competitor_list,omitempty"`
}

func (x *CompetitorList) Reset() {
	*x = CompetitorList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompetitorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitorList) ProtoMessage() {}

func (x *CompetitorList) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitorList.ProtoReflect.Descriptor instead.
func (*CompetitorList) Descriptor() ([]byte, []int) {
	return file_competitor_proto_rawDescGZIP(), []int{1}
}

func (x *CompetitorList) GetCompetitorList() []*Competitor {
	if x != nil {
		return x.CompetitorList
	}
	return nil
}

type CreateByCompetitorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Competitor string `protobuf:"bytes,1,opt,name=competitor,proto3" json:"competitor,omitempty"`
}

func (x *CreateByCompetitorRequest) Reset() {
	*x = CreateByCompetitorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateByCompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateByCompetitorRequest) ProtoMessage() {}

func (x *CreateByCompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateByCompetitorRequest.ProtoReflect.Descriptor instead.
func (*CreateByCompetitorRequest) Descriptor() ([]byte, []int) {
	return file_competitor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateByCompetitorRequest) GetCompetitor() string {
	if x != nil {
		return x.Competitor
	}
	return ""
}

type CompetitorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Competitor *Competitor `protobuf:"bytes,1,opt,name=competitor,proto3" json:"competitor,omitempty"`
}

func (x *CompetitorRequest) Reset() {
	*x = CompetitorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competitor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitorRequest) ProtoMessage() {}

func (x *CompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitorRequest.ProtoReflect.Descriptor instead.
func (*CompetitorRequest) Descriptor() ([]byte, []int) {
	return file_competitor_proto_rawDescGZIP(), []int{3}
}

func (x *CompetitorRequest) GetCompetitor() *Competitor {
	if x != nil {
		return x.Competitor
	}
	return nil
}

type CompetitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// bool error = 1;
	// string message = 2;
	Competitor *Competitor `protobuf:"bytes,1,opt,name=competitor,proto3" json:"competitor,omitempty"`
}

func (x *CompetitorResponse) Reset() {
	*x = CompetitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competitor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompetitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitorResponse) ProtoMessage() {}

func (x *CompetitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitorResponse.ProtoReflect.Descriptor instead.
func (*CompetitorResponse) Descriptor() ([]byte, []int) {
	return file_competitor_proto_rawDescGZIP(), []int{4}
}

func (x *CompetitorResponse) GetCompetitor() *Competitor {
	if x != nil {
		return x.Competitor
	}
	return nil
}

type CompetitorIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *CompetitorIdRequest) Reset() {
	*x = CompetitorIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competitor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompetitorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitorIdRequest) ProtoMessage() {}

func (x *CompetitorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitorIdRequest.ProtoReflect.Descriptor instead.
func (*CompetitorIdRequest) Descriptor() ([]byte, []int) {
	return file_competitor_proto_rawDescGZIP(), []int{5}
}

func (x *CompetitorIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCompetitorStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
}

func (x *GetCompetitorStreamRequest) Reset() {
	*x = GetCompetitorStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_competitor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCompetitorStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitorStreamRequest) ProtoMessage() {}

func (x *GetCompetitorStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitorStreamRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitorStreamRequest) Descriptor() ([]byte, []int) {
	return file_competitor_proto_rawDescGZIP(), []int{6}
}

func (x *GetCompetitorStreamRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

var File_competitor_proto protoreflect.FileDescriptor

var file_competitor_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x22, 0xad,
	0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6f, 0x5f,
	0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x73, 0x65, 0x6f, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x51,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x3f, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f,
	0x72, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x3b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x43, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x4b,
	0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74,
	0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x4c, 0x0a, 0x12, 0x43,
	0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x36, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f,
	0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x32, 0x9c, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65,
	0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72,
	0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x38, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x6f, 0x72, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65,
	0x74, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69,
	0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_competitor_proto_rawDescOnce sync.Once
	file_competitor_proto_rawDescData = file_competitor_proto_rawDesc
)

func file_competitor_proto_rawDescGZIP() []byte {
	file_competitor_proto_rawDescOnce.Do(func() {
		file_competitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_competitor_proto_rawDescData)
	})
	return file_competitor_proto_rawDescData
}

var file_competitor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_competitor_proto_goTypes = []interface{}{
	(*Competitor)(nil),                 // 0: competitor.Competitor
	(*CompetitorList)(nil),             // 1: competitor.CompetitorList
	(*CreateByCompetitorRequest)(nil),  // 2: competitor.CreateByCompetitorRequest
	(*CompetitorRequest)(nil),          // 3: competitor.CompetitorRequest
	(*CompetitorResponse)(nil),         // 4: competitor.CompetitorResponse
	(*CompetitorIdRequest)(nil),        // 5: competitor.CompetitorIdRequest
	(*GetCompetitorStreamRequest)(nil), // 6: competitor.GetCompetitorStreamRequest
}
var file_competitor_proto_depIdxs = []int32{
	0, // 0: competitor.CompetitorList.competitor_list:type_name -> competitor.Competitor
	0, // 1: competitor.CompetitorRequest.competitor:type_name -> competitor.Competitor
	0, // 2: competitor.CompetitorResponse.competitor:type_name -> competitor.Competitor
	0, // 3: competitor.CompetitorService.Create:input_type -> competitor.Competitor
	0, // 4: competitor.CompetitorService.Update:input_type -> competitor.Competitor
	5, // 5: competitor.CompetitorService.GetById:input_type -> competitor.CompetitorIdRequest
	5, // 6: competitor.CompetitorService.GetListByChannel:input_type -> competitor.CompetitorIdRequest
	0, // 7: competitor.CompetitorService.Create:output_type -> competitor.Competitor
	0, // 8: competitor.CompetitorService.Update:output_type -> competitor.Competitor
	0, // 9: competitor.CompetitorService.GetById:output_type -> competitor.Competitor
	1, // 10: competitor.CompetitorService.GetListByChannel:output_type -> competitor.CompetitorList
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_competitor_proto_init() }
func file_competitor_proto_init() {
	if File_competitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_competitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Competitor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompetitorList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competitor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateByCompetitorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competitor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompetitorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competitor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompetitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competitor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompetitorIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_competitor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCompetitorStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_competitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_competitor_proto_goTypes,
		DependencyIndexes: file_competitor_proto_depIdxs,
		MessageInfos:      file_competitor_proto_msgTypes,
	}.Build()
	File_competitor_proto = out.File
	file_competitor_proto_rawDesc = nil
	file_competitor_proto_goTypes = nil
	file_competitor_proto_depIdxs = nil
}
