// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: keyword.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeywordServiceClient is the client API for KeywordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeywordServiceClient interface {
	Create(ctx context.Context, in *Keyword, opts ...grpc.CallOption) (*KeywordResponse, error)
	CreateByKeyword(ctx context.Context, in *CreateByKeywordRequest, opts ...grpc.CallOption) (*KeywordResponse, error)
	Update(ctx context.Context, in *Keyword, opts ...grpc.CallOption) (*KeywordResponse, error)
	// Get
	GetById(ctx context.Context, in *GetKeywordByIdRequest, opts ...grpc.CallOption) (*KeywordResponse, error)
	GetStream(ctx context.Context, in *GetKeywordStreamRequest, opts ...grpc.CallOption) (KeywordService_GetStreamClient, error)
}

type keywordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeywordServiceClient(cc grpc.ClientConnInterface) KeywordServiceClient {
	return &keywordServiceClient{cc}
}

func (c *keywordServiceClient) Create(ctx context.Context, in *Keyword, opts ...grpc.CallOption) (*KeywordResponse, error) {
	out := new(KeywordResponse)
	err := c.cc.Invoke(ctx, "/keyword.KeywordService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keywordServiceClient) CreateByKeyword(ctx context.Context, in *CreateByKeywordRequest, opts ...grpc.CallOption) (*KeywordResponse, error) {
	out := new(KeywordResponse)
	err := c.cc.Invoke(ctx, "/keyword.KeywordService/CreateByKeyword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keywordServiceClient) Update(ctx context.Context, in *Keyword, opts ...grpc.CallOption) (*KeywordResponse, error) {
	out := new(KeywordResponse)
	err := c.cc.Invoke(ctx, "/keyword.KeywordService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keywordServiceClient) GetById(ctx context.Context, in *GetKeywordByIdRequest, opts ...grpc.CallOption) (*KeywordResponse, error) {
	out := new(KeywordResponse)
	err := c.cc.Invoke(ctx, "/keyword.KeywordService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keywordServiceClient) GetStream(ctx context.Context, in *GetKeywordStreamRequest, opts ...grpc.CallOption) (KeywordService_GetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &KeywordService_ServiceDesc.Streams[0], "/keyword.KeywordService/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &keywordServiceGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeywordService_GetStreamClient interface {
	Recv() (*KeywordResponse, error)
	grpc.ClientStream
}

type keywordServiceGetStreamClient struct {
	grpc.ClientStream
}

func (x *keywordServiceGetStreamClient) Recv() (*KeywordResponse, error) {
	m := new(KeywordResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeywordServiceServer is the server API for KeywordService service.
// All implementations must embed UnimplementedKeywordServiceServer
// for forward compatibility
type KeywordServiceServer interface {
	Create(context.Context, *Keyword) (*KeywordResponse, error)
	CreateByKeyword(context.Context, *CreateByKeywordRequest) (*KeywordResponse, error)
	Update(context.Context, *Keyword) (*KeywordResponse, error)
	// Get
	GetById(context.Context, *GetKeywordByIdRequest) (*KeywordResponse, error)
	GetStream(*GetKeywordStreamRequest, KeywordService_GetStreamServer) error
	mustEmbedUnimplementedKeywordServiceServer()
}

// UnimplementedKeywordServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeywordServiceServer struct {
}

func (UnimplementedKeywordServiceServer) Create(context.Context, *Keyword) (*KeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedKeywordServiceServer) CreateByKeyword(context.Context, *CreateByKeywordRequest) (*KeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateByKeyword not implemented")
}
func (UnimplementedKeywordServiceServer) Update(context.Context, *Keyword) (*KeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedKeywordServiceServer) GetById(context.Context, *GetKeywordByIdRequest) (*KeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedKeywordServiceServer) GetStream(*GetKeywordStreamRequest, KeywordService_GetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedKeywordServiceServer) mustEmbedUnimplementedKeywordServiceServer() {}

// UnsafeKeywordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeywordServiceServer will
// result in compilation errors.
type UnsafeKeywordServiceServer interface {
	mustEmbedUnimplementedKeywordServiceServer()
}

func RegisterKeywordServiceServer(s grpc.ServiceRegistrar, srv KeywordServiceServer) {
	s.RegisterService(&KeywordService_ServiceDesc, srv)
}

func _KeywordService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Keyword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyword.KeywordService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordServiceServer).Create(ctx, req.(*Keyword))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeywordService_CreateByKeyword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateByKeywordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordServiceServer).CreateByKeyword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyword.KeywordService/CreateByKeyword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordServiceServer).CreateByKeyword(ctx, req.(*CreateByKeywordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeywordService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Keyword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyword.KeywordService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordServiceServer).Update(ctx, req.(*Keyword))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeywordService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeywordByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyword.KeywordService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordServiceServer).GetById(ctx, req.(*GetKeywordByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeywordService_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetKeywordStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeywordServiceServer).GetStream(m, &keywordServiceGetStreamServer{stream})
}

type KeywordService_GetStreamServer interface {
	Send(*KeywordResponse) error
	grpc.ServerStream
}

type keywordServiceGetStreamServer struct {
	grpc.ServerStream
}

func (x *keywordServiceGetStreamServer) Send(m *KeywordResponse) error {
	return x.ServerStream.SendMsg(m)
}

// KeywordService_ServiceDesc is the grpc.ServiceDesc for KeywordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeywordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keyword.KeywordService",
	HandlerType: (*KeywordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _KeywordService_Create_Handler,
		},
		{
			MethodName: "CreateByKeyword",
			Handler:    _KeywordService_CreateByKeyword_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _KeywordService_Update_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _KeywordService_GetById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _KeywordService_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "keyword.proto",
}
