// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/hidenari-yuda/go-docker-template/interfaces"
	"github.com/hidenari-yuda/go-docker-template/interfaces/handler"
	"github.com/hidenari-yuda/go-docker-template/interfaces/repository"
	"github.com/hidenari-yuda/go-docker-template/usecase"
	"github.com/hidenari-yuda/go-docker-template/usecase/interactor"
)

// Injectors from wire.go:

// User
//
func InitializeUserHandler(db interfaces.SQLExecuter, fb usecase.Firebase) handler.UserHandler {
	userRepository := repository.NewUserRepositoryImpl(db)
	userInteractor := interactor.NewUserInteractorImpl(fb, userRepository)
	userHandler := handler.NewUserHandlerImpl(userInteractor)
	return userHandler
}

// User
//
func InitializeUserInteractor(db interfaces.SQLExecuter, fb usecase.Firebase) interactor.UserInteractor {
	userRepository := repository.NewUserRepositoryImpl(db)
	userInteractor := interactor.NewUserInteractorImpl(fb, userRepository)
	return userInteractor
}

// wire.go:

var wireSet = wire.NewSet(handler.WireSet, interactor.WireSet, repository.WireSet)
